sensors:
  - realsense_pointcloud

realsense_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /filtered_pointcloud
  max_range: 1.5
  frame_subsample: 1
  point_subsample: 1
  padding_offset: 0.02
  padding_scale: 1.0
  max_update_rate: 10.0
  filtered_cloud_topic: /filtered_pointcloud
